### ISSUE TITLE
Not clear how to set up custom theme.

### ISSUE THREAD

**Issue by payneio** [justkey007/fomantic-ui-sass#3]
Thanks for doing all this! I was just contemplating porting myself, when I found your package. It's great.

I'm not clear on how to change custom variables, though. This is in the `README.md`:

"If you want to modify in your personalized file a variable which can generate derivatives like the colors and their variants please do it and put in front your personalized file in order to have conforming derivatives."

What I want to do is modify `$button-background-color` in `custom/elements/button.scss`, and have it be used throughout the default theme. If I import the custom theme afterwards, it only overwrites the single variable, but not, e.g. `$button-background: $button-background-color $button-background-image !default` in `themes/default/elements/button.variables.css`.

If I import my custom theme first, it get's overwritten by the default vars. So... I'd like to avoid putting all derivatives in the custom theme... but not sure how.

**Comment by justkey007** [comment]
Hello, I just read you and I want to clarify that the problem is to find a good order for the default and custom variables files. Moreover it was my biggest difficulty to rename and place the variables in the right order because the source written in LESS does not know this problem. I was able to translate by writing scripts on the fly with regular expressions to automate the task a bit.

"If I import my custom theme first, it will be overwritten by the default vars ... So ... I'd like to avoid putting all the derivatives in the custom theme ... but not sure how." ==> Normally the default variables are followed by the flag "! Default" and custom ones should normally overwrite them if the compilation went well (You can try with node-sass). The problem is in order for the functions or property css that are composed of other variables.

I will see after this side and the pull requests are also welcome. Thank you

**Comment by payneio** [comment]
Oh, I see! I wasn't clear on the behavior of `!default`. So, you are suggesting to first set up all the `_variables` and then apply your `custom` theme which will overwrite the variables, but if your custom variable is needed in the computation of _variables, then put it before the _variables import?

I am trying with flipping that approach and it seems to work well so far: Since `!default` will only overwrite if it isn't set, I pull in my custom theme *first* and then pull in the default _variables. If I want to use a default _variable in my custom theme, I just make sure to pull that particular one in first. So far, that has only resulted in my pulling in a few default global _variables, so everything works well.

I think it may be helpful to split the default theme into two directories... one that has all the base variable definitions without the `!default`s and another that is the actual default theme. Then the setup would look something like this:

@import 'base_variables' (these variables either don't change, like exact-pixels, or don't include a bunch of derivatives, so I can overwrite any one easily with my custom theme)
@import 'custom'
@import 'default' (now, I can set any variables that I haven't already chosen)
@import 'semantic'
